### ISSUE TITLE
Image files are not integrated in the profile, but simply linked

### ISSUE THREAD

**Issue by davidp57** [mhwlng/streamdeck-elite#12]
When selecting images to decorate the buttons, they are linked instead of being copied in the profile folder like in the default streamdeck buttons (and all the other plugins I've seen).
The net result is that, if I export my profile for a friend, the images will be missing. 
Also, I cannot delete the folder where I stored the images, else the profile will be incomplete.

![image](https://user-images.githubusercontent.com/172286/85337943-bf661100-b4e1-11ea-9373-2296e8bedae8.png)

**Comment by davidp57** [comment]
this is a small problem, thanks for your work on this project !

**Comment by mhwlng** [comment]
I am not aware of any other way to do this?

The plugins that you are referring to, probably edit the image in this way:
![image](https://user-images.githubusercontent.com/1388886/85360363-41256100-b519-11ea-820d-d9c63a8cb4c7.png)

I can't use that method, because the button image has to be controlled by the game state and not by pressing the button

**Comment by Behelith-Vanyar** [comment]
I understand that due to how the plugin is implemented it's not possible to integrate the images.
But would it be possible to use a relative path instead of an absolute path?
As in the screenshots of the OP I can't see the names of the images assigned to each state because the path is too long.
There is a workaround: select/copy/paste the path to e.g. notepad, so the issue is not critical, rather a QoL thing.

PS: Hope you don't mind my reply on this closed issue, but I didn't want to create a new one.

**Comment by mhwlng** [comment]
no the elgato sdk doesn't allow  relative paths
