### ISSUE TITLE
Controller Limpet button does not seem to work

### ISSUE THREAD

**Issue by veldthui** [mhwlng/streamdeck-elite#15]
Mapped controller Limpet to Firegroup F Primary. In the firegroups in Elite the controller limpet is mapped to group F and is showing 1 (primary).
I am in fire group A with my weapons and just after destroying a ship go to send limpets out to collect the goodies and push the button. The screen seems to flip to the fire group with the limpets assigned but does not actually launch a limpet and then goes back to the original firegroup.

**Comment by mhwlng** [comment]
I assume that you have a (secondary) keyboard binding for your primary fire button?
If there is only a binding for a joystick/controller button, then it won't work.

If that's not the problem, then maybe it's a timing issue between switching fire groups and pressing the primary fire keyboard button.

What happens if you first manually go to the correct fire group, and only then press the streamdeck button ?
(Then, the only thing that the streamdeck has to do is : 'press' the primary fire keyboard button)

**Comment by veldthui** [comment]
There was a binding but it was for the mouse button. I read joystick/controller so thought the mouse button was okay as I was using the mouse on some occasions. I remapped the primary and secondary to the keyboard and it works as it should.
Thanks.
