### ISSUE TITLE
Toggle Buttons Don't Control Corresponding Devices

### ISSUE THREAD

**Issue by rosscarlson** [mhwlng/streamdeck-elite#61]
I'm not sure if this is a bug or feature - the Toggle Button functions are getting data from the game, say if I deploy/retract my landing gear the button/image changes correctly but pressing the button does nothing. I'm honestly not sure if it's supposed to - I feel like it naturally would - so is this a bug or feature?

Have the latest version installed as of this post and I see nothing in the log file (in Roaming\Elgato\StreamDeck\Plugins\com.mhwlng.elite.sdPlugin - I don't have a "logs" directory there, I do have "archive" that has a file from a previous Windows install dated back to 2022). Given I'm getting the correct status from the game I'm not sure if it's due to my *very* custom bindings or not.

Any input is much appreciated.

**Comment by mhwlng** [comment]
in that case you probably don't have all 4 key bindings set to custom ? (as described on the github page.)

The plugin log file will show you which key binding files are being used.

(otherwise there may be a key combination for that particular function that the plugin can't simulate?)

also, are you sure that you have an actual (secondary) keyboard button defined for the function? a mouse/joystick button won't work.
