### ISSUE TITLE
Some shortcuts don't work

### ISSUE THREAD

**Issue by geraldlec** [mhwlng/streamdeck-elite#65]
Hello,
I've tried searching on my own, but it seems that certain shortcuts like "energy cell activation" or "kit medical", on foot, no longer work.
The others are ok.
I'm also having a problem with the "ship return/recall", but it seems to be coming from the game > joystick shortcuts don't work either, no nothing to do with this plugin.
Thanks for your help,
Gérald.

**Comment by mhwlng** [comment]
You'll have to provide more information. 
Do the key combinations work if you press them on your keyboard?

do you see 4x 'custom' bindings in elite. if not then this plugin doesn't work!
-General
-Ship
-Srv
-Onfoot

Only, if that is not the problem, then please post all the files in %LocalAppData%\Frontier Developments\Elite Dangerous\Options\Bindings\ here
and list which key combinations don't work for you (that work on your keyboard)

**Comment by geraldlec** [comment]
Hello,

Key bind had dissapeared for the energy battery and med kit. It is OK.

There is still 2 things that don't work:
- the return/recall on foot. It works with the VRS not the human. In human config I don't see the keybind in the game.
- the night vision: it works from ship and VRS. Not the human, the human has it own keybind, I tried the same as ship/vrs, then different from ship/vrs > does not work.

SHIP/VRS

	<NightVisionToggle>
		<Primary Device="044FB352" Key="Joy_16" />
		<Secondary Device="Keyboard" Key="Key_N" />
	</NightVisionToggle>

HUMANOID

	<HumanoidToggleNightVisionButton>
		<Primary Device="Keyboard" Key="Key_N">
			<Modifier Device="Keyboard" Key="Key_RightShift" />
		</Primary>
		<Secondary Device="044FB353" Key="Joy_16" />
	</HumanoidToggleNightVisionButton>

**Comment by mhwlng** [comment]
please post all the files in %LocalAppData%\Frontier Developments\Elite Dangerous\Options\Bindings\ here

**Comment by geraldlec** [comment]
[Bindings.zip](https://github.com/user-attachments/files/15923951/Bindings.zip)

**Comment by mhwlng** [comment]
does everything work when you press the keyboard button ?

' In human config I don't see the keybind in the game.'
I don't know what you mean? 
I only see one binding 'RecallDismissShip' ? 
If there is another, that is not in the plugin, then please tell me where it is in the binding file?

I don't see any problem in the code: both HumanoidToggleNightVisionButton and RecallDismissShip are handled just like any other button.

you can try both the 'on foot night vision' static button and the 'night vision' toggle button. 
for HumanoidToggleNightVisionButton

note that the toggle night vision button does not change active state on foot. 
that is a limitation in the game, not in the plugin.
![image](https://github.com/mhwlng/streamdeck-elite/assets/1388886/6ef051ab-a987-45bc-b9f7-2f3e8363e7b3)


If the problem is, that the button must be pressed longer, before it works in the game, then please try to add the button definition, that you can find in static.html, in the plugin directory, into repeatingstatic.cshtml
You can press repeatingstatic buttons longer on the streamdeck. 
For static button, a longer press has no effect.

Restart streamdeck.exe after editing  repeatingstatic.cshtml

Otherwise, I have no idea what I could do to fix your problem...

all buttons are handled exactly the same

The only special logic is for NightVisionToggle toggle button:

   case "NightVisionToggle":
       if (EliteData.StatusData.OnFoot)
           StreamDeckCommon.SendKeypress(Program.Binding[BindingType.OnFoot].HumanoidToggleNightVisionButton);
       else
           StreamDeckCommon.SendKeypress(Program.Binding[BindingType.Ship].NightVisionToggle);
       break;

**Comment by geraldlec** [comment]
That's what I explained - for return/recall ship
- in menu game where you setup the keybinds: there is no "return/recall ship" for human. In ship/vrs: button and plugin work, In human: nothing work > need to use the "insight wheel". That could explain why the plugin can't work.

For nightvision, will try your tip this evening.

Thanks
